spring.application.name=maintenanceapp

spring.datasource.url=jdbc:postgresql://localhost:5432/maintenance_db
spring.datasource.username=postgres
spring.datasource.password=Asser123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver